language: python
python:
#  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
env:
  - PYMONGO_VERSION=2.7
  - PYMONGO_VERSION=3.1.1
# command to install dependencies
services:
  - mongodb
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pymongo==$PYMONGO_VERSION
# command to run tests
script: coverage run --source=./ manage.py test 
after_success: 
  - coverage report
  - coveralls
