# Travis build script for django-mongolog
#
# Support for python 3.2 and 3.3 discontinued because django officially dropped support in 1.8
# https://docs.djangoproject.com/en/1.9/releases/1.9/#django-1-9-release-notes
language: python
python:
#  - "2.6"  # Just to old to support
  - "2.7"
  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
env:
  - PYMONGO="==2.4" DJANGO="==0.9"
  - PYMONGO=">=2.4" DJANGO=">=0.9" 
# command to install dependencies
services:
  - mongodb
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pymongo$PYMONGO_VERSION
  - pip install django$VERSION
  - pip freeze
# command to run tests
script: coverage run --source=./ manage.py test 
#script: python manage.py test
after_success: 
  - coverage report
  - coveralls
